version: '3.4'

services:

  auth-server:
    image: authorizer
    container_name: "authorizer"
    build: ./
    command: ./app
    ports:
      - 8001:8000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "auth-mongo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=editt
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet